const CORS = {
  'Content-Type': 'application/json; charset=utf-8',
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Methods': 'POST,OPTIONS',
  'Access-Control-Allow-Headers': 'Content-Type, Authorization',
  'Access-Control-Max-Age': '86400',
};

const CHAT_VERSION = '2026-09-24-live-page-aware-assistant-v9';
const DHAKA_OFFSET_MINUTES = 360;
const VIDEO_STATUS_COLUMNS = ['full_video_status','short_ex_status','short_top_status','style_ex_status','style_top_status'];
const json = (data,status=200)=>new Response(JSON.stringify(data),{status,headers:CORS});
function normalizeText(v){return String(v??'').toLowerCase().normalize('NFKC').replace(/[“”‘’]/g,"'").replace(/[।,!?;:()[\]{}"'`]/g,' ').replace(/\s+/g,' ').trim()}
function hasAny(t,words){const q=normalizeText(t);return words.some(w=>q.includes(normalizeText(w)))}
function channelOf(r){return String(r?.channel??'').trim().toUpperCase()}
function rowName(r){for(const k of ['name','project_name','project','title','content_name'])if(r?.[k]!=null&&String(r[k]).trim())return String(r[k]).trim();return `Post #${r?.id??'—'}`}
function postType(r){for(const k of ['content_type','type','post_type'])if(r?.[k]!=null&&String(r[k]).trim())return String(r[k]).trim();return '—'}
function statusValue(v){return normalizeText(v).replace(/_/g,' ').trim()}
function contentVideoStatus(row){const values=VIDEO_STATUS_COLUMNS.map(k=>statusValue(row?.[k])).filter(Boolean);if(!values.length)return 'Listed';if(values.every(v=>['record','recorded','recorder','recording'].includes(v)))return 'Recorder';if(values.every(v=>['not set','none','null','n/a','listed'].includes(v)))return 'Listed';return 'Running'}
function detectIntent(question){const q=normalizeText(question);return{count:hasAny(q,['কয়টা','কতটি','কতগুলো','কয়টি','কত','how many','count','total','number of']),list:hasAny(q,['নাম','নামগুলো','list','show','দাও','দেখাও','কে কে','which','what are','কোনগুলো','কী কী','কি কি']),schedule:hasAny(q,['schedule','scheduled','শিডিউল','শিডিউল করা','scheduled post','scheduled posts','শিডিউল পোস্ট']),upload:hasAny(q,['upload','uploaded','আপলোড','আপলোড হয়েছে','আপলোড হয়েছে','আপলোড করা']),recorder:hasAny(q,['record','recorded','recorder','recording','রেকর্ড','রেকর্ডার','রেকর্ড করা','রেকর্ড হয়েছে','রেকর্ড হয়েছে']),running:hasAny(q,['running','run','চলছে','রানিং','চলমান']),listed:hasAny(q,['listed','লিস্টেড']),editing:hasAny(q,['editing done','edited','edit done','editing','এডিট','এডিটিং','এডিট করা','এডিট শেষ']),client:hasAny(q,['client','clients','ক্লায়েন্ট','ক্লায়েন্ট']),book:hasAny(q,['book','books','বুক','বই']),post:hasAny(q,['post','posts','পোস্ট','পোস্টগুলো']),content:hasAny(q,['content','কনটেন্ট','কন্টেন্ট']),today:hasAny(q,['আজ','আজকে','today']),tomorrow:hasAny(q,['আগামীকাল','কাল','tomorrow']),channel:q.includes('hhd')?'HHD':q.includes('bhd')?'BHD':q.includes('dhd')?'DHD':null}}
function tokenFromRequest(r){const h=String(r.headers.get('Authorization')||'');return h.startsWith('Bearer ')?h.slice(7).trim():''}
function decode64(v){const n=String(v||'').replace(/-/g,'+').replace(/_/g,'/');return atob(n+'='.repeat((4-n.length%4)%4))}
async function sha256(v){const d=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(String(v)));return[...new Uint8Array(d)].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function requireAuth(r,db){const token=tokenFromRequest(r);if(!token)return null;const p=token.split('.');if(p.length!==2)return null;try{const payload=decode64(p[0]);const [idText,expText]=payload.split('.');const id=Number(idText),exp=Number(expText);if(!Number.isInteger(id)||!Number.isFinite(exp)||exp<=Math.floor(Date.now()/1000))return null;const user=await db.prepare('SELECT id, display_name, email, photo, role, password_hash FROM users WHERE id = ? LIMIT 1').bind(id).first();if(!user?.password_hash)return null;return await sha256(`${payload}.${String(user.password_hash)}`)===p[1]?user:null}catch{return null}}
const SENSITIVE=/password|password_hash|password_salt|token|secret|api[_-]?key|authorization|cookie/i;
function sanitize(v,k=''){if(SENSITIVE.test(String(k)))return'[REDACTED]';if(Array.isArray(v))return v.map(x=>sanitize(x));if(v&&typeof v==='object'){const o={};for(const[a,b]of Object.entries(v))o[a]=sanitize(b,a);return o}return v}
function quoteIdent(n){return`"${String(n).replaceAll('"','""')}"`}
async function loadDatabase(db){const s=await db.prepare("SELECT name,type,sql FROM sqlite_master WHERE name NOT LIKE 'sqlite_%' AND type IN ('table','view') ORDER BY type,name").all();const tables={},schemas=[];for(const x of s.results||[]){const n=String(x?.name||'').trim();if(!n)continue;schemas.push({name:n,type:String(x?.type||''),sql:String(x?.sql||'')});try{const r=await db.prepare(`SELECT * FROM ${quoteIdent(n)}`).all();tables[n]=(r.results||[]).map(v=>sanitize(v))}catch{tables[n]=[]}}return{generated_at:new Date().toISOString(),schemas,counts:Object.fromEntries(Object.entries(tables).map(([k,v])=>[k,v.length])),tables}}
function contentRows(db){return Array.isArray(db?.tables?.contents)?db.tables.contents:[]}
function postRows(db){return Array.isArray(db?.tables?.posts)?db.tables.posts:[]}
function todayDhaka(){return new Date(Date.now()+DHAKA_OFFSET_MINUTES*60000).toISOString().slice(0,10)}
function tomorrowDhaka(){return new Date(Date.now()+(24*60+DHAKA_OFFSET_MINUTES)*60000).toISOString().slice(0,10)}
function dateInfo(v){if(v==null||!String(v).trim())return null;const t=String(v).trim();const m=t.match(/^(\d{4}-\d{2}-\d{2})[ T](\d{2}:\d{2})(?::(\d{2}))?/);if(m)return{date:m[1],time:m[2],raw:t};const ms=Date.parse(t);if(Number.isNaN(ms))return null;const s=new Date(ms+DHAKA_OFFSET_MINUTES*60000).toISOString();return{date:s.slice(0,10),time:s.slice(11,16),raw:t}}
function uploadDate(r){for(const k of ['uploaded_at','upload_date','uploaded_on','created_at','updated_at']){const d=dateInfo(r?.[k]);if(d)return{...d,source:k}}return null}
function calendarDate(r){return dateInfo(r?.scheduled_at)}
function isScheduled(r){return statusValue(r?.status)==='scheduled'}
function isUploaded(r){return['uploaded','upload','posted','published'].includes(statusValue(r?.status))}
function formatDate(d){return d?`${d.date} ${d.time||''}`.trim():'date/time not set'}
function formatPost(r,d=calendarDate(r)||uploadDate(r)){return`${rowName(r)} [${channelOf(r)||'—'}] — ${postType(r)} — ${String(r?.status||'—').trim()} — ${formatDate(d)}`}
function parseQuestionDate(question){const q=normalizeText(question);const iso=q.match(/\b(20\d{2})[-\/](\d{1,2})[-\/](\d{1,2})\b/);if(iso)return`${iso[1]}-${String(iso[2]).padStart(2,'0')}-${String(iso[3]).padStart(2,'0')}`;const num=q.match(/\b(\d{1,2})[-\/](\d{1,2})(?:[-\/](20\d{2}))?\b/);if(num){const d=+num[1],m=+num[2],y=num[3]?+num[3]:new Date().getFullYear();if(d>=1&&d<=31&&m>=1&&m<=12)return`${y}-${String(m).padStart(2,'0')}-${String(d).padStart(2,'0')}`}const months={january:1,jan:1,february:2,feb:2,march:3,mar:3,april:4,apr:4,may:5,june:6,jun:6,july:7,jul:7,august:8,aug:8,september:9,sep:9,sept:9,october:10,oct:10,november:11,nov:11,december:12,dec:12,'জানুয়ারি':1,'জানুয়ারি':1,'ফেব্রুয়ারি':2,'ফেব্রুয়ারি':2,'মার্চ':3,'এপ্রিল':4,'মে':5,'জুন':6,'জুলাই':7,'আগস্ট':8,'সেপ্টেম্বর':9,'অক্টোবর':10,'নভেম্বর':11,'ডিসেম্বর':12};const p=Object.keys(months).sort((a,b)=>b.length-a.length).join('|');let m=q.match(new RegExp(`(?:^|\\s)(\\d{1,2})\\s+(${p})(?:\\s+(20\\d{2}))?(?:$|\\s)`,'i'));if(m){const d=+m[1],mo=months[m[2].toLowerCase()],y=m[3]?+m[3]:new Date().getFullYear();if(mo&&d>=1&&d<=31)return`${y}-${String(mo).padStart(2,'0')}-${String(d).padStart(2,'0')}`}m=q.match(new RegExp(`(?:^|\\s)(${p})\\s+(\\d{1,2})(?:\\s*,?\\s*(20\\d{2}))?(?:$|\\s)`,'i'));if(m){const mo=months[m[1].toLowerCase()],d=+m[2],y=m[3]?+m[3]:new Date().getFullYear();if(mo&&d>=1&&d<=31)return`${y}-${String(mo).padStart(2,'0')}-${String(d).padStart(2,'0')}`}if(hasAny(q,['আজ','আজকে','today']))return todayDhaka();if(hasAny(q,['আগামীকাল','tomorrow']))return tomorrowDhaka();return null}
function exactContent(question,db){const i=detectIntent(question);let rows=contentRows(db);if(i.channel)rows=rows.filter(r=>channelOf(r)===i.channel);let label=null;if(i.recorder){label='Recorder/Recorded';rows=rows.filter(r=>contentVideoStatus(r)==='Recorder')}else if(i.running){label='Running';rows=rows.filter(r=>contentVideoStatus(r)==='Running')}else if(i.listed){label='Listed';rows=rows.filter(r=>contentVideoStatus(r)==='Listed')}if(label&&i.count)return`${i.channel?i.channel+'-এ ':''}মোট ${rows.length}টি ${label} video আছে।`;if(label&&i.list)return rows.length?rows.slice(0,100).map((r,n)=>`${n+1}. ${rowName(r)} [${channelOf(r)||'—'}] — Video: ${contentVideoStatus(r)}`).join('\n'):'Live D1 data অনুযায়ী কোনো matching content পাওয়া যায়নি।';return null}
function exactPosts(question,db){const i=detectIntent(question),q=normalizeText(question);const explicitSchedule=i.schedule;const target=parseQuestionDate(question);const asksDate=hasAny(q,['কবে','কখন','সময়','সময়','time','তারিখ','date']);const asksPost=i.post||hasAny(q,['ভিডিও','video','videos']);const idMatch=q.match(/\b([a-z]{3}\d+)\b/i);if(!explicitSchedule&&!i.upload&&!target&&!(asksDate&&asksPost)&&!idMatch)return null;let rows=postRows(db);if(i.channel)rows=rows.filter(r=>channelOf(r)===i.channel);if(explicitSchedule)rows=rows.filter(isScheduled);else if(i.upload)rows=rows.filter(isUploaded);if(target)rows=rows.filter(r=>(explicitSchedule?calendarDate(r):calendarDate(r)||uploadDate(r))?.date===target);if(idMatch)rows=rows.filter(r=>normalizeText(rowName(r))===normalizeText(idMatch[1]));if(idMatch&&rows.length&&(i.upload||asksDate)){const r=rows[0];const d=i.upload?uploadDate(r):calendarDate(r);return d?`${rowName(r)} ${i.upload?'আপলোড হয়েছে':'scheduled হয়েছে'} ${formatDate(d)}।`:`${rowName(r)}-এর ${i.upload?'upload':'schedule'} date/time D1 data-তে পাওয়া যায়নি।`};if((explicitSchedule||target)&&i.count)return`${target?target+' তারিখে ':''}${rows.length}টি ${explicitSchedule?'scheduled':'calendar'} post আছে${i.channel?' '+i.channel+'-এ':''}.`;if(explicitSchedule||target){if(!rows.length)return`${target?target+' তারিখে ':''}কোনো ${explicitSchedule?'scheduled':'calendar'} post পাওয়া যায়নি।`;return`${target?target+' তারিখে ':'মোট '}${rows.length}টি ${explicitSchedule?'scheduled':'calendar'} post:\n${rows.slice(0,100).map((r,n)=>`${n+1}. ${formatPost(r)}`).join('\n')}`}return null}
function exactClientBook(question,db){const i=detectIntent(question);if(!i.client&&!i.book)return null;const names=i.client?['clients','client']:['books','book'];let rows=[];for(const n of names){if(Array.isArray(db?.tables?.[n])){rows=db.tables[n];break}}if(!rows.length)return null;if(i.count)return`Live D1 data অনুযায়ী মোট ${rows.length}টি ${i.client?'client':'book'} আছে।`;if(i.list)return rows.slice(0,100).map((r,n)=>`${n+1}. ${rowName(r)}`).join('\n');return null}
function deterministicAnswer(question,db){return exactContent(question,db)||exactPosts(question,db)||exactClientBook(question,db)}
const INSTRUCTIONS=`You are the private AI assistant for the Content Schedule Manager. The LIVE D1 database snapshot is the only source of truth. Content Page uses contents; one row is one content/video. Content status logic: all five status fields blank/not-set => Listed; all five are Record/Recorded/Recorder/Recording => Recorder; otherwise => Running. Calendar uses posts. A post is Scheduled ONLY when status is exactly Scheduled and scheduled_at is present. Uploaded/Posted posts are never Scheduled merely because scheduled_at exists. For upload questions use uploaded_at/upload_date/uploaded_on/created_at/updated_at. Never invent counts, dates, names, statuses or times. Reply in the user's language/style.`
function geminiModels(env){return[String(env.GEMINI_MODEL||'').trim(),'gemini-2.5-flash','gemini-2.0-flash'].filter((v,i,a)=>v&&a.indexOf(v)===i)}
function geminiText(d){return(d?.candidates||[]).flatMap(c=>c?.content?.parts||[]).map(p=>typeof p?.text==='string'?p.text:'').filter(Boolean).join('\n').trim()}
async function askGemini(env,input){const key=String(env.GEMINI_API_KEY||env.Gemini_API_Key||env.Gemini_API_KEY||'').trim();if(!key)throw Object.assign(new Error('Gemini API key is not configured'),{code:'missing_gemini_key'});let last=null;for(const model of geminiModels(env)){try{const r=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(model)}:generateContent`,{method:'POST',headers:{'Content-Type':'application/json','x-goog-api-key':key},body:JSON.stringify({systemInstruction:{parts:[{text:INSTRUCTIONS}]},contents:[{role:'user',parts:[{text:input}]}],generationConfig:{maxOutputTokens:3000,temperature:0.1}})});const raw=await r.text();if(r.ok){const d=JSON.parse(raw),a=geminiText(d);if(a)return{answer:a,model};throw new Error('Gemini returned an empty answer')}let msg=`Gemini request failed (${r.status})`,code='';try{const d=JSON.parse(raw);msg=d?.error?.message||msg;code=d?.error?.status||d?.error?.code||''}catch{}last=Object.assign(new Error(msg),{status:r.status,code});if(r.status===400||r.status===404)continue;break}catch(e){last=e}}throw last||new Error('Gemini request failed')}
export async function handleChat(request,env){if(request.method==='OPTIONS')return new Response(null,{status:204,headers:CORS});if(request.method!=='POST')return json({error:'method not allowed',version:CHAT_VERSION},405);if(!env?.DB)return json({error:'D1 binding DB is not configured',version:CHAT_VERSION},500);const user=await requireAuth(request,env.DB);if(!user)return json({error:'authentication required'},401);const body=await request.json().catch(()=>({}));const question=String(body.message||'').trim();if(!question)return json({error:'message required'},400);if(question.length>3000)return json({error:'message is too long'},400);let database;try{database=await loadDatabase(env.DB)}catch(e){return json({error:'database read failed',details:e?.message||String(e),version:CHAT_VERSION},500)}const deterministic=deterministicAnswer(question,database);if(deterministic)return json({ok:true,answer:deterministic,model:'deterministic-d1',provider:'google_gemini',data_source:'live_d1',assistant_version:CHAT_VERSION,ai_available:true,table_counts:database.counts});const history=Array.isArray(body.history)?body.history.slice(-10):[];const conversation=history.filter(x=>x?.role&&x?.text).map(x=>`${String(x.role).toUpperCase()}: ${String(x.text)}`).join('\n');const input=['CURRENT USER QUESTION:',question,'','RECENT CONVERSATION:',conversation||'none','','LIVE DATABASE SNAPSHOT:',JSON.stringify(database),'','IMPORTANT: answer only from the live snapshot.'].join('\n');try{const r=await askGemini(env,input);return json({ok:true,answer:r.answer,model:r.model,provider:'google_gemini',data_source:'live_d1',assistant_version:CHAT_VERSION,ai_available:true,table_counts:database.counts})}catch(e){return json({ok:true,answer:'Live D1 data পাওয়া গেছে, কিন্তু এই প্রশ্নের নির্ভুল উত্তর তৈরি করা যায়নি।',model:'local-d1-fallback',provider:'google_gemini',data_source:'live_d1',assistant_version:CHAT_VERSION,ai_available:false,ai_reason:e?.code||'gemini_unavailable',table_counts:database.counts})}}
