const CORS={"Content-Type":"application/json; charset=utf-8","Access-Control-Allow-Origin":"*","Access-Control-Allow-Methods":"POST,OPTIONS","Access-Control-Allow-Headers":"Content-Type, Authorization"};
const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:CORS});
const tokenFromRequest=r=>{const h=String(r.headers.get("Authorization")||"");return h.startsWith("Bearer ")?h.slice(7).trim():""};
function b64(v){v=String(v||"").replace(/-/g,"+").replace(/_/g,"/");return atob(v+"=".repeat((4-v.length%4)%4))}
async function sha(v){const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(String(v)));return [...new Uint8Array(d)].map(x=>x.toString(16).padStart(2,"0")).join("")}
async function auth(r,db){const t=tokenFromRequest(r),p=t.split(".");if(p.length!==2)return null;try{const [idText,expText]=b64(p[0]).split("."),id=Number(idText),exp=Number(expText);if(!Number.isInteger(id)||!Number.isFinite(exp)||exp<=Date.now()/1000)return null;const u=await db.prepare("SELECT id,email,password_hash FROM users WHERE id=? LIMIT 1").bind(id).first();if(!u?.password_hash)return null;return await sha(`${b64(p[0])}.${u.password_hash}`)===p[1]?u:null}catch{return null}}
const statuses=x=>[x.full_video_status,x.short_ex_status,x.short_top_status,x.style_ex_status,x.style_top_status].map(v=>String(v||"").trim());
function stage(x){const s=statuses(x);if(s.every(v=>!v||v.toLowerCase()==="not set"))return"Listed";if(s.every(v=>v.toLowerCase()==="record"))return"Recorder";return"Running"}
function content(x){const s=statuses(x);return{id:x.id,name:x.name,channel:x.channel||"",stage:stage(x),full_video:s[0]||"Not set",short_ex:s[1]||"Not set",short_top:s[2]||"Not set",style_ex:s[3]||"Not set",style_top:s[4]||"Not set"}}
const channel=q=>{const m=String(q||"").match(/\b(HHD|BHD|DHD)\b/i);return m?m[1].toUpperCase():null};
function videoStage(q){const l=String(q).toLowerCase();if(/\blisted\b|not\s*set|ready/.test(l))return"Listed";if(/\brecorder\b|\brecorded\b|\brecord\b/.test(l))return"Recorder";if(/\brunning\b|in\s*progress|working/.test(l))return"Running";return null}
function videoAnswer(q,cs){const l=q.toLowerCase(),ch=channel(q),st=videoStage(q);if(!/video|content/.test(l)||(!ch&&!st))return null;const rows=cs.filter(x=>!ch||x.channel.toUpperCase()===ch);if(st&&/how many|count|total/.test(l))return`${ch?ch+" ":""}${st} Video: ${rows.filter(x=>x.stage===st).length}`;if(st){const a=rows.filter(x=>x.stage===st);return`${ch?ch+" ":""}${st} Video: ${a.length}\n\n${a.length?a.map((x,i)=>`${i+1}. ${x.name}`).join("\n"):"No matching videos found."}`};if(ch&&/how many|count|total/.test(l))return`${ch} Total Content: ${rows.length}`;if(ch)return`${ch} Content: ${rows.length}\n\n${rows.map((x,i)=>`${i+1}. ${x.name} — ${x.stage}`).join("\n")}`;return null}
function dhakaKey(v){const d=new Date(v);if(Number.isNaN(d.getTime()))return null;return new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Dhaka",year:"numeric",month:"2-digit",day:"2-digit"}).format(d)}
function time(v){const d=new Date(v);if(Number.isNaN(d.getTime()))return String(v||"");return new Intl.DateTimeFormat("en-US",{timeZone:"Asia/Dhaka",hour:"numeric",minute:"2-digit"}).format(d)}
function schedules(posts,ch=null,date=null){return posts.filter(p=>p?.scheduled_at&&(!ch||String(p.channel||"").toUpperCase()===ch)&&(!date||dhakaKey(p.scheduled_at)===date)).sort((a,b)=>new Date(a.scheduled_at)-new Date(b.scheduled_at))}
function scheduleAnswer(q,posts){const l=q.toLowerCase(),ch=channel(q),asks=/schedule|scheduled|calendar|today|tomorrow|post|আজ|ajke|কাল|kal/.test(l);if(!asks)return null;const today=/\btoday\b|আজ|ajke/.test(l),tomorrow=/\btomorrow\b|আগামীকাল/.test(l),count=/how many|count|total/.test(l);if(count&&!today&&!tomorrow){const a=schedules(posts,ch);return`${ch?ch+" ":""}Total Scheduled Posts: ${a.length}`};if(today||tomorrow){const d=new Date();if(tomorrow)d.setUTCDate(d.getUTCDate()+1);const key=new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Dhaka",year:"numeric",month:"2-digit",day:"2-digit"}).format(d),a=schedules(posts,ch,key),title=`${ch?ch+" ":""}${tomorrow?"Tomorrow":"Today"} Scheduled Posts`;if(!a.length)return`${title}: 0\n\nNo scheduled posts found.`;return`${title}: ${a.length}\n\n${a.map((p,i)=>`${i+1}. ${p.project_name||"Untitled"}${p.channel?` [${p.channel}]`:""} — ${time(p.scheduled_at)}${p.content_type?` — ${p.content_type}`:""}${p.platform?` — ${p.platform}`:""}`).join("\n")}`};if(/show|list|which|what|কি|কী|দেখাও|লিস্ট/.test(l)){const a=schedules(posts,ch);return`${ch?ch+" ":""}Scheduled Posts: ${a.length}\n\n${a.length?a.map((p,i)=>`${i+1}. ${p.project_name||"Untitled"}${p.channel?` [${p.channel}]`:""} — ${time(p.scheduled_at)}`).join("\n"):"No scheduled posts found."}`};return null}
function text(r){return(r?.output||[]).flatMap(x=>x?.content||[]).filter(x=>x?.type==="output_text").map(x=>x.text).join("\n").trim()}
export async function handleChat(request,env){if(request.method==="OPTIONS")return new Response(null,{status:204,headers:CORS});if(request.method!=="POST")return json({error:"method not allowed"},405);if(!env?.DB)return json({error:"D1 binding DB is not configured"},500);if(!await auth(request,env.DB))return json({error:"authentication required"},401);const p=await request.json().catch(()=>({})),q=String(p.message||"").trim();if(!q)return json({error:"message required"},400);if(q.length>2000)return json({error:"message is too long"},400);const [cr,pr]=await Promise.all([env.DB.prepare("SELECT id,name,channel,full_video_status,short_ex_status,short_top_status,style_ex_status,style_top_status,poster_status FROM contents ORDER BY id DESC LIMIT 1000").all(),env.DB.prepare("SELECT id,project_name,content_type,channel,platform,status,scheduled_at,uploaded_link FROM posts ORDER BY id DESC LIMIT 5000").all()]);const cs=(cr.results||[]).map(content),posts=pr.results||[];const direct=videoAnswer(q,cs)||scheduleAnswer(q,posts);if(direct)return json({answer:direct});const summary=Object.fromEntries(["HHD","BHD","DHD"].map(c=>{const a=cs.filter(x=>x.channel.toUpperCase()===c);return[c,{total:a.length,listed:a.filter(x=>x.stage==="Listed").length,recorder:a.filter(x=>x.stage==="Recorder").length,running:a.filter(x=>x.stage==="Running").length}] }));const key=String(env.OPENAI_API_KEY||"").trim();if(!key)return json({error:"AI chatbot is not configured. Add OPENAI_API_KEY to the Cloudflare Worker secrets."},503);const ctx={channel_summary:summary,contents:cs,posts};const response=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{Authorization:`Bearer ${key}`,"Content-Type":"application/json"},body:JSON.stringify({model:String(env.OPENAI_MODEL||"gpt-5.6-luna"),instructions:"You are the private assistant for this Content Schedule Manager. Use only the live database context. Never invent data. Answer in the user's language/style. Scheduled posts are posts with a non-empty scheduled_at, interpreted in Asia/Dhaka. The chatbot is read-only.",input:`${q}\n\nLIVE DATA:\n${JSON.stringify(ctx)}`,store:false,max_output_tokens:1200})});const raw=await response.text();if(!response.ok){let e="OpenAI request failed";try{e=JSON.parse(raw)?.error?.message||e}catch{}return json({error:e},502)}const answer=text(JSON.parse(raw));return answer?json({answer}):json({error:"The AI returned an empty response."},502)}
