const jsonHeaders = {
  'Content-Type':'application/json; charset=utf-8',
  'Access-Control-Allow-Origin':'*','Access-Control-Allow-Methods':'GET,POST,PUT,DELETE,OPTIONS','Access-Control-Allow-Headers':'Content-Type, Authorization','Access-Control-Max-Age':'86400',
};
const json=(data,status=200,extra={})=>new Response(JSON.stringify(data),{status,headers:{...jsonHeaders,...extra}});
const noContent=()=>new Response(null,{status:204,headers:jsonHeaders});
const validId=value=>/^\d+$/.test(String(value));
const parseDate=value=>{if(!value)return null;const d=new Date(value);return Number.isNaN(d.getTime())?null:d};
const settingObject=rows=>{const out={};for(const row of rows)out[row.key]=String(row.value||'').split(',').map(v=>v.trim()).filter(Boolean);return out};
function formatSuggestedDate(value){const d=parseDate(value);if(!d)return String(value||'');return d.toLocaleString('en-US',{weekday:'short',month:'short',day:'numeric',year:'numeric',hour:'numeric',minute:'2-digit'});}
async function body(request){try{return await request.json()}catch{return {}}}
async function handle(request,env){
  if(request.method==='OPTIONS')return noContent();
  if(!env.DB)return json({error:'D1 binding DB is not configured'},500);
  const url=new URL(request.url),path=url.pathname.replace(/\/+$/,'')||'/',method=request.method,db=env.DB;
  if(method==='GET'&&path==='/api/health'){const row=await db.prepare('SELECT 1 AS ok').first();return json({ok:row?.ok===1,database:'D1'})}
  if(method==='GET'&&path==='/api/posts'){const r=await db.prepare(`SELECT p.*,u.display_name AS owner FROM posts p LEFT JOIN users u ON p.created_by=u.id ORDER BY p.scheduled_at IS NULL,p.scheduled_at`).all();return json(r.results||[])}
  if(method==='GET'&&path==='/api/posts/project-suggestions'){
    const q=String(url.searchParams.get('query')||'').trim();if(!q)return json([]);
    const r=await db.prepare(`SELECT project_name,scheduled_at,channel,status FROM posts WHERE project_name IS NOT NULL AND lower(project_name) LIKE ? ORDER BY scheduled_at IS NULL,scheduled_at DESC`).bind(`%${q.toLowerCase()}%`).all();
    const map={};for(const row of r.results||[]){const name=row.project_name;if(!map[name])map[name]={project_name:name,schedules:[],count:0};map[name].count++;if(row.scheduled_at)map[name].schedules.push(row)}
    return json(Object.values(map).map(item=>{const latest=item.schedules[0]||null;return{project_name:item.project_name,count:item.count,last_scheduled_at:latest?.scheduled_at||null,last_scheduled_dates:item.schedules.slice(0,5).map(s=>({scheduled_at:s.scheduled_at,label:formatSuggestedDate(s.scheduled_at),channel:s.channel||'',status:s.status||''}))}}));
  }
  if(method==='POST'&&path==='/api/posts/bulk'){const p=await body(request);if(!p.project_name||!p.start_date)return json({error:'project_name and start_date required'},400);const start=parseDate(p.start_date),end=p.end_date?parseDate(p.end_date):null;if(!start||(p.end_date&&!end))return json({error:'invalid date'},400);if(end&&end<start)return json({error:'end_date must be on or after start_date'},400);const days=Array.isArray(p.days_of_week)?p.days_of_week.map(Number).filter(n=>Number.isInteger(n)&&n>=0&&n<=6):[];const max=Math.min(Math.max(Number(p.occurrences)||365,1),1000);const statements=[];const cursor=new Date(start);let count=0;while((end?cursor<=end:count<max)&&count<max){if(days.length===0||days.includes(cursor.getDay())){statements.push(db.prepare(`INSERT INTO posts (project_name,content_type,channel,platform,status,scheduled_at,created_by) VALUES (?,?,?,?, 'Scheduled',?,?)`).bind(p.project_name,p.content_type||null,p.channel||null,p.platform||null,cursor.toISOString(),p.created_by||null));count++}cursor.setDate(cursor.getDate()+1)}if(statements.length)await db.batch(statements);const created=await db.prepare(`SELECT * FROM posts WHERE project_name=? ORDER BY id DESC LIMIT ?`).bind(p.project_name,count).all();return json({created_count:count,created:(created.results||[]).reverse()},201)}
  if(method==='GET'&&path==='/api/templates'){const r=await db.prepare('SELECT * FROM templates ORDER BY created_at DESC').all();return json(r.results||[])}
  if(method==='POST'&&path==='/api/templates'){const p=await body(request);if(!p.name)return json({error:'name required'},400);const r=await db.prepare(`INSERT INTO templates (name,content_type,channel,platform,project_id,created_by) VALUES (?,?,?,?,?,?)`).bind(p.name,p.content_type||null,p.channel||null,p.platform||null,p.project_id||null,p.created_by||null).run();return json(await db.prepare('SELECT * FROM templates WHERE id=?').bind(r.meta.last_row_id).first(),201)}
  const tm=path.match(/^\/api\/templates\/(\d+)$/);if(method==='DELETE'&&tm){const r=await db.prepare('DELETE FROM templates WHERE id=?').bind(Number(tm[1])).run();return r.meta.changes?json({ok:true}):json({error:'template not found'},404)}
  const nm=path.match(/^\/api\/posts\/(\d+)\/notes$/);if(nm){const id=Number(nm[1]);if(method==='GET'){const r=await db.prepare(`SELECT pn.*,u.display_name AS user_name FROM post_notes pn LEFT JOIN users u ON pn.user_id=u.id WHERE pn.post_id=? ORDER BY pn.created_at DESC`).bind(id).all();return json(r.results||[])}if(method==='POST'){const p=await body(request);if(!String(p.message||'').trim())return json({error:'message required'},400);if(!await db.prepare('SELECT id FROM posts WHERE id=?').bind(id).first())return json({error:'post not found'},404);const r=await db.prepare('INSERT INTO post_notes (post_id,user_id,message) VALUES (?,?,?)').bind(id,p.user_id||null,String(p.message).trim()).run();return json(await db.prepare(`SELECT pn.*,u.display_name AS user_name FROM post_notes pn LEFT JOIN users u ON pn.user_id=u.id WHERE pn.id=?`).bind(r.meta.last_row_id).first(),201)}}
  if(method==='GET'&&path==='/api/dashboard/due-soon'){const r=await db.prepare(`SELECT p.*,u.display_name AS owner FROM posts p LEFT JOIN users u ON p.created_by=u.id WHERE p.scheduled_at IS NOT NULL AND p.scheduled_at>=datetime('now') AND p.scheduled_at<datetime('now','+7 days') AND (p.status IS NULL OR p.status!='Uploaded') ORDER BY p.scheduled_at ASC LIMIT 50`).all();return json(r.results||[])}
  if(method==='POST'&&path==='/api/overdue/check'){const r=await db.prepare(`UPDATE posts SET is_overdue=CASE WHEN status='Scheduled' AND scheduled_at IS NOT NULL AND scheduled_at<datetime('now') THEN 1 ELSE 0 END`).run();return json({updated:r.meta.changes})}
  if(method==='POST'&&path==='/api/posts'){const p=await body(request);if(!p.project_name)return json({error:'project_name required'},400);if(p.scheduled_at&&!parseDate(p.scheduled_at))return json({error:'invalid scheduled_at'},400);const r=await db.prepare(`INSERT INTO posts (project_name,content_type,channel,platform,status,scheduled_at,uploaded_link,notes,created_by,recurring_rule) VALUES (?,?,?,?,?,?,?,?,?,?)`).bind(p.project_name,p.content_type||null,p.channel||null,p.platform||null,p.status||'Listed',p.scheduled_at||null,p.uploaded_link||null,p.notes||null,p.created_by||null,p.recurring_rule||null).run();const row=await db.prepare('SELECT * FROM posts WHERE id=?').bind(r.meta.last_row_id).first();await db.prepare('INSERT INTO audit(post_id,action,payload,actor) VALUES (?,?,?,?)').bind(row.id,'create',JSON.stringify(row),p.created_by||'system').run();return json(row,201)}
  const pm=path.match(/^\/api\/posts\/(\d+)$/);if(pm){const id=Number(pm[1]);if(method==='PUT'){const p=await body(request);if(p.scheduled_at&&!parseDate(p.scheduled_at))return json({error:'invalid scheduled_at'},400);if(!await db.prepare('SELECT id FROM posts WHERE id=?').bind(id).first())return json({error:'post not found'},404);await db.prepare(`UPDATE posts SET project_name=?,content_type=?,channel=?,platform=?,status=?,scheduled_at=?,uploaded_link=?,notes=?,recurring_rule=?,updated_at=datetime('now') WHERE id=?`).bind(p.project_name||null,p.content_type||null,p.channel||null,p.platform||null,p.status||null,p.scheduled_at||null,p.uploaded_link||null,p.notes||null,p.recurring_rule||null,id).run();const row=await db.prepare('SELECT * FROM posts WHERE id=?').bind(id).first();await db.prepare('INSERT INTO audit(post_id,action,payload,actor) VALUES (?,?,?,?)').bind(id,'update',JSON.stringify(row),p.updated_by||'system').run();return json(row)}if(method==='DELETE'){const row=await db.prepare('SELECT * FROM posts WHERE id=?').bind(id).first();if(!row)return json({error:'post not found'},404);const p=await body(request);await db.prepare('INSERT INTO audit(post_id,action,payload,actor) VALUES (?,?,?,?)').bind(id,'delete',JSON.stringify(row),p.actor||'system').run();await db.prepare('DELETE FROM posts WHERE id=?').bind(id).run();return json({ok:true})}}
  const dm=path.match(/^\/api\/posts\/(\d+)\/duplicate$/);if(method==='POST'&&dm){const id=Number(dm[1]),row=await db.prepare('SELECT * FROM posts WHERE id=?').bind(id).first();if(!row)return json({error:'post not found'},404);const p=await body(request);const r=await db.prepare(`INSERT INTO posts (project_name,content_type,channel,platform,status,scheduled_at,uploaded_link,notes,created_by,recurring_rule) VALUES (?,?,?,?, 'Listed',NULL,NULL,?,?,?)`).bind(row.project_name,row.content_type,row.channel,row.platform,row.notes,p.created_by||row.created_by,row.recurring_rule).run();return json(await db.prepare('SELECT * FROM posts WHERE id=?').bind(r.meta.last_row_id).first(),201)}
  const um=path.match(/^\/api\/posts\/(\d+)\/mark-uploaded$/);if(method==='POST'&&um){const id=Number(um[1]);if(!await db.prepare('SELECT id FROM posts WHERE id=?').bind(id).first())return json({error:'post not found'},404);const p=await body(request);await db.prepare("UPDATE posts SET status='Uploaded',uploaded_link=?,is_overdue=0,updated_at=datetime('now') WHERE id=?").bind(p.uploaded_link||null,id).run();return json(await db.prepare('SELECT * FROM posts WHERE id=?').bind(id).first())}
  if(method==='GET'&&path==='/api/settings'){const r=await db.prepare('SELECT key,value FROM settings').all();return json(settingObject(r.results||[]))}
  const sm=path.match(/^\/api\/settings\/([a-zA-Z0-9_-]+)$/);if(method==='PUT'&&sm){const p=await body(request);const values=Array.isArray(p)?p.map(v=>String(v).trim()).filter(Boolean):[];await db.prepare('INSERT OR REPLACE INTO settings(key,value) VALUES (?,?)').bind(sm[1],values.join(',')).run();return json({key:sm[1],values})}
  if(method==='GET'&&path==='/api/users'){const r=await db.prepare('SELECT * FROM users ORDER BY created_at DESC').all();return json(r.results||[])}
  if(method==='POST'&&path==='/api/invite'){const p=await body(request),email=String(p.email||'').trim().toLowerCase();if(!/^\S+@\S+\.\S+$/.test(email))return json({error:'valid email required'},400);const bytes=new Uint8Array(32);crypto.getRandomValues(bytes);const token=[...bytes].map(b=>b.toString(16).padStart(2,'0')).join('');const r=await db.prepare('INSERT INTO invites(email,role,token) VALUES (?,?,?)').bind(email,p.role||'manager',token).run();return json(await db.prepare('SELECT id,email,role,status,created_at FROM invites WHERE id=?').bind(r.meta.last_row_id).first(),201)}
  if(method==='GET'&&path==='/api/invites'){const r=await db.prepare('SELECT id,email,role,status,created_at FROM invites ORDER BY created_at DESC').all();return json(r.results||[])}
  if(method==='GET'&&path==='/api/summary'){const r=await db.batch([db.prepare('SELECT COUNT(*) AS c FROM posts'),db.prepare("SELECT COUNT(*) AS c FROM posts WHERE scheduled_at>=datetime('now') AND scheduled_at<datetime('now','+7 days')"),db.prepare("SELECT COUNT(*) AS c FROM posts WHERE status='Uploaded' AND strftime('%Y-%m',created_at)=strftime('%Y-%m','now')"),db.prepare("SELECT COUNT(*) AS c FROM posts WHERE status='Listed'"),db.prepare("SELECT COUNT(*) AS c FROM posts WHERE is_overdue=1")]);return json({total:r[0].results?.[0]?.c||0,scheduledWeek:r[1].results?.[0]?.c||0,uploadedMonth:r[2].results?.[0]?.c||0,listedCount:r[3].results?.[0]?.c||0,overdue:r[4].results?.[0]?.c||0})}
  return json({error:'not found'},404);
}
export default{fetch:handle};
