import React, {useEffect, useState, useMemo} from 'react'
import api from '../api'
import LinkActions from '../components/LinkActions'

const PALETTE = ['#6c5ce7','#3b82f6','#10b981','#f59e0b','#ef4444','#14b8a6','#8b5cf6','#ec4899'];
const WEEKDAYS = ['Mon','Tue','Wed','Thu','Fri','Sat','Sun'];
function buildCounts(posts, field){ return posts.reduce((acc,post)=>{ const key=post?.[field]||'Unknown'; acc[key]=(acc[key]||0)+1; return acc; },{}); }
function getWeekday(post){ if(!post?.scheduled_at)return null; const d=new Date(post.scheduled_at); if(Number.isNaN(d.getTime()))return null; return d.toLocaleDateString('en-US',{weekday:'short'}); }
function weeklyCounts(posts){ const result=Object.fromEntries(WEEKDAYS.map(d=>[d,0])); posts.forEach(p=>{const day=getWeekday(p); if(day)result[day]=(result[day]||0)+1}); return result; }
function monthCounts(posts){ const result=Array.from({length:12},(_,i)=>({label:new Date(2000,i,1).toLocaleDateString('en-US',{month:'short'}),value:0})); posts.forEach(p=>{if(!p?.scheduled_at)return;const d=new Date(p.scheduled_at);if(!Number.isNaN(d.getTime()))result[d.getMonth()].value+=1}); return result; }
function weeklyTypeCounts(posts){ const start=new Date();const day=start.getDay();const diff=day===0?-6:1-day;start.setDate(start.getDate()+diff);start.setHours(0,0,0,0);const end=new Date(start);end.setDate(start.getDate()+7);const result={};posts.forEach(p=>{if(!p?.scheduled_at)return;const d=new Date(p.scheduled_at);if(Number.isNaN(d.getTime())||d<start||d>=end)return;const type=p.content_type||'Unknown';result[type]=(result[type]||0)+1});return result; }
function HoverTooltip({x,y,label,value,width=110}){const tx=Math.max(4,Math.min(x-width/2,640-width-4));const ty=Math.max(4,y-50);return <g pointerEvents="none"><rect x={tx} y={ty} width={width} height="40" rx="7" fill="#fff" stroke="#d9dee8"/><text x={tx+10} y={ty+16} fill="#111827" fontSize="11" fontWeight="700">{label}</text><text x={tx+10} y={ty+31} fill="#667085" fontSize="11" fontWeight="600">{value} post{value===1?'':'s'}</text></g>}
function AreaChart({title,entries}){const [hovered,setHovered]=useState(null);const values=entries.map(([,v])=>v);const max=Math.max(...values,1);const width=640,height=250,left=46,right=22,top=22,bottom=38;const chartW=width-left-right,chartH=height-top-bottom;const points=entries.map(([,v],i)=>({x:entries.length===1?width/2:left+(i/Math.max(entries.length-1,1))*chartW,y:top+chartH-(v/max)*chartH,value:v}));const line=points.map((p,i)=>`${i?'L':'M'} ${p.x} ${p.y}`).join(' ');const area=`${line} L ${points.at(-1)?.x||left} ${top+chartH} L ${points[0]?.x||left} ${top+chartH} Z`;const gradientId=`grad-${title.replace(/[^a-z0-9]/gi,'-')}`;return <div className="chart card dashboard-chart-card"><div className="card-header"><h3>{title}</h3><span className="chart-total">{values.reduce((a,b)=>a+b,0)}</span></div><div className="reference-chart-wrap"><svg viewBox={`0 0 ${width} ${height}`} className="reference-chart" role="img" aria-label={title}><defs><linearGradient id={gradientId} x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="#3b82f6" stopOpacity="0.36"/><stop offset="100%" stopColor="#3b82f6" stopOpacity="0.08"/></linearGradient></defs>{[0,.25,.5,.75,1].map((r,i)=>{const y=top+chartH-r*chartH;return <g key={i}><line x1={left} x2={width-right} y1={y} y2={y} className="reference-grid-line"/><text x="8" y={y+4} className="reference-axis-label">{Math.round(max*r)}</text></g>})}<path d={area} fill={`url(#${gradientId})`} className="reference-area"/><path d={line} className="reference-line"/>{points.map((p,i)=>{const active=hovered===i;return <g key={i} onMouseEnter={()=>setHovered(i)} onMouseLeave={()=>setHovered(null)} onFocus={()=>setHovered(i)} onBlur={()=>setHovered(null)}><circle cx={p.x} cy={p.y} r={active?7:5} className="reference-point" tabIndex="0" role="button" aria-label={`${entries[i][0]}: ${p.value}`}/>{active&&<HoverTooltip x={p.x} y={p.y} label={entries[i][0]} value={p.value}/>}</g>})}{entries.map(([label],i)=><text key={label} x={points[i].x} y={height-10} textAnchor="middle" className="reference-axis-label">{label}</text>)}</svg></div></div>}
function BarChart({title,entries,colors=PALETTE}){const [hovered,setHovered]=useState(null);const max=Math.max(...entries.map(([,v])=>v),1);return <div className="chart card dashboard-chart-card"><div className="card-header"><h3>{title}</h3><span className="chart-total">{entries.reduce((a,[,v])=>a+v,0)}</span></div><div className="reference-column-chart"><div className="column-grid">{[0,.25,.5,.75,1].map((r,i)=><span key={i} className="column-grid-line" style={{bottom:`${r*100}%`}}/>)}</div><div className="column-bars">{entries.map(([label,value],i)=>{const active=hovered===i;return <div key={label} className="column-group" onMouseEnter={()=>setHovered(i)} onMouseLeave={()=>setHovered(null)} tabIndex="0" role="button" aria-label={`${label}: ${value}`} onFocus={()=>setHovered(i)} onBlur={()=>setHovered(null)}><div className="column-value" style={{height:`${Math.max(6,(value/max)*100)}%`,background:colors[i%colors.length]}}>{active&&<span className="column-tooltip">{label}: {value}</span>}</div><div className="column-label" title={label}>{label}</div></div>})}</div></div></div>}

export default function Dashboard(){
 const [summary,setSummary]=useState({}); const [posts,setPosts]=useState([]); const [dueSoon,setDueSoon]=useState([]); const [search,setSearch]=useState(''); const [searchOpen,setSearchOpen]=useState(false);
 const loadDashboard=()=>{api.get('/summary').then(r=>setSummary(r.data||{})).catch(()=>{});api.get('/posts').then(r=>setPosts(Array.isArray(r.data)?r.data:[])).catch(()=>setPosts([]));api.get('/dashboard/due-soon').then(r=>setDueSoon(Array.isArray(r.data)?r.data.slice(0,5):[])).catch(()=>setDueSoon([]));};
 useEffect(()=>{loadDashboard()},[])
 useEffect(()=>{const onKey=e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();setSearchOpen(true);setTimeout(()=>document.querySelector('#dashboard-universal-search')?.focus(),0)}if(e.key==='Escape')setSearchOpen(false)};window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey)},[])
 const channelCounts=useMemo(()=>buildCounts(posts,'channel'),[posts]); const typeCounts=useMemo(()=>buildCounts(posts,'content_type'),[posts]); const monthlyCounts=useMemo(()=>monthCounts(posts),[posts]); const weeklyTypes=useMemo(()=>weeklyTypeCounts(posts),[posts]);
 const stats=[{key:'total',label:'Total posts',value:summary.total||0,icon:'📁',trend:'+4%'},{key:'scheduledWeek',label:'Scheduled this week',value:summary.scheduledWeek||0,icon:'🗓️',trend:'+1%'},{key:'uploadedMonth',label:'Uploaded this month',value:summary.uploadedMonth||0,icon:'⬆️',trend:'-2%'},{key:'listedCount',label:'Listed',value:summary.listedCount||0,icon:'📝',trend:'+0%'}];
 const searchQuery=search.trim().toLowerCase(); const results=useMemo(()=>{if(!searchQuery)return [];return posts.filter(p=>[p.project_name,p.content_type,p.channel,p.platform,p.status,p.owner,p.notes,p.uploaded_link,p.scheduled_at].some(v=>String(v??'').toLowerCase().includes(searchQuery))).slice(0,8)},[posts,searchQuery]);
 const openResult=()=>{setSearchOpen(false);localStorage.setItem('list_filter_search',search);window.dispatchEvent(new CustomEvent('navigateToList'));setTimeout(()=>window.dispatchEvent(new CustomEvent('openSearchResult')),60)};
 return <div className="page dashboard">
   <div className="dashboard-search-bar"><div className="dashboard-search-inner"><span className="dashboard-search-icon">⌕</span><input id="dashboard-universal-search" value={search} onFocus={()=>setSearchOpen(true)} onChange={e=>{setSearch(e.target.value);setSearchOpen(true)}} placeholder="Search projects, content, channels, platforms, status…" aria-label="Universal search"/><kbd>⌘K</kbd>{search&&<button type="button" className="dashboard-search-clear" onMouseDown={e=>e.preventDefault()} onClick={()=>setSearch('')} aria-label="Clear search">×</button>}</div>{searchOpen&&searchQuery&&<div className="dashboard-search-results">{results.length?results.map(p=><button type="button" key={p.id} className="dashboard-search-result" onMouseDown={e=>e.preventDefault()} onClick={openResult}><div className="dashboard-search-result-main"><strong>{p.project_name||'(untitled)'}</strong><span>{[p.content_type,p.channel,p.platform].filter(Boolean).join(' · ')}</span></div><span className={`search-status ${String(p.status||'').toLowerCase()}`}>{p.status||'—'}</span></button>):<div className="dashboard-search-empty">No matching posts found.</div>}</div>}</div>
   <div className="dashboard-header" style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:12,marginBottom:18}}><div><h2 style={{margin:'0 0 4px'}}>Dashboard</h2><div style={{color:'var(--muted)',fontSize:13}}>Manage projects and scheduled content from one place.</div></div><div style={{display:'flex',gap:8,flexWrap:'wrap',justifyContent:'flex-end'}}><button className="btn-secondary" type="button" onClick={()=>window.dispatchEvent(new CustomEvent('requestBulkCreate'))}>Bulk Create</button><button className="btn-primary" type="button" onClick={()=>window.dispatchEvent(new CustomEvent('requestNewPost'))}>+ New Scheduled Post</button></div></div>
   <div className="cards">{stats.map(s=><div className="card stat-card" key={s.key}><div className="stat-badge">{s.icon}</div><div className="stat-body"><div className="stat-label">{s.label}</div><div className="stat-value">{s.value}</div><div className="stat-trend">{s.trend}</div></div></div>)}</div>
   <div className="charts dashboard-chart-grid reference-dashboard-grid"><AreaChart title="Posts by Channel" entries={Object.entries(channelCounts)}/><AreaChart title="Posts by Content Type" entries={Object.entries(typeCounts)}/><AreaChart title="Total Content Monthly" entries={monthlyCounts.map(x=>[x.label,x.value])}/><BarChart title="Weekly Content Type" entries={Object.entries(weeklyTypes)}/></div>
   <div className="recent card"><h3>Recent activity</h3><ul>{posts.slice(-10).reverse().map(p=><li key={p.id}>{p.project_name||'(untitled)'} — {p.status} — {p.scheduled_at||'no date'}</li>)}</ul></div>
   <div className="card due-soon"><h3>Due Today / This Week</h3><ul>{dueSoon.map(p=><li key={p.id} style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><div style={{display:'flex',alignItems:'center',gap:8}}><div>{p.project_name||'(untitled)'} — {p.channel} — {p.scheduled_at}</div><div className="link-text" title={p.uploaded_link||''}>{p.uploaded_link||''}</div><LinkActions url={p.uploaded_link}/></div><div><button type="button" onClick={()=>api.post('/posts/'+p.id+'/mark-uploaded',{uploaded_link:p.uploaded_link||null}).then(()=>{setDueSoon(ds=>ds.filter(x=>x.id!==p.id));loadDashboard()})}>Mark Uploaded</button></div></li>)}</ul><div><button type="button" onClick={()=>window.dispatchEvent(new CustomEvent('navigateToList'))}>View all</button></div></div>
 </div>
}
