name = "contentmanagement-api"
main = "src/entry.js"
workers_dev = true
compatibility_date = "2026-08-22"

[triggers]
crons = ["* * * * *"]

[[d1_databases]]
binding = "DB"
database_name = "contentmanagement"
database_id = "9439d0eb-fff4-42ce-98ae-15095b4ac57a"
